knp_snappy:
    pdf:
        enabled:    true
        binary:     '"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"'
        options:    
            no-images: true

    image:
        enabled:    true
        binary:     '"C:\Program Files\wkhtmltopdf\bin\wkhtmltoimage.exe"'
        options:    
            no-images: true

